import {
  FileQuestion,
  Stethoscope,
  Activity,
  ClipboardList,
  Target,
  Compass,
  Heart,
  Syringe,
  Pill,
  Microscope,
  Radio,
  Baby,
  Bone,
  Eye,
  Ear,
} from 'lucide-react';

export const examTypes = [
  {
    id: 'pyq',
    title: 'Previous Year Questions',
    description: 'University papers with textbook references',
    icon: FileQuestion,
    color: 'from-amber-500 to-orange-600',
    stats: { total: 15000, attempted: 2340, mastered: 890 },
    sources: ['NEET-PG', 'INICET', 'AIIMS', 'JIPMER', 'DNB-CET'],
    href: '/exam-centre/pyq',
    isAvailable: true,
  },
  {
    id: 'mcq',
    title: 'MCQ Practice',
    description: 'Topic-wise questions with explanations',
    icon: ClipboardList,
    color: 'from-blue-500 to-cyan-600',
    stats: { total: 25000, attempted: 5420, mastered: 2100 },
    sources: ['Standard Textbooks', 'High-Yield Topics', 'Recent Updates'],
    href: '/exam-centre/mcq',
    isAvailable: true,
  },
  {
    id: 'patient-sim',
    title: 'Patient Simulator',
    description: 'Real-life case simulations',
    icon: Stethoscope,
    color: 'from-emerald-500 to-teal-600',
    stats: { total: 500, attempted: 45, mastered: 12 },
    features: ['History Taking', 'Examination', 'Investigations', 'Management'],
    href: '/exam-centre/simulator/acute-appendicitis',
    isAvailable: true,
  },
  {
    id: 'patient-flow',
    title: 'Patient Flows',
    description: 'Clinical decision pathways',
    icon: Activity,
    color: 'from-purple-500 to-pink-600',
    stats: { total: 200, attempted: 28, mastered: 8 },
    features: ['Diagnostic Algorithms', 'Treatment Protocols', 'Emergency Pathways'],
    href: '/exam-centre/flow/upper-gi-bleeding',
    isAvailable: true,
  },
  {
    id: 'practical',
    title: 'Practical Exams',
    description: 'OSCE & clinical skills assessment',
    icon: Target,
    color: 'from-rose-500 to-red-600',
    stats: { total: 150, attempted: 22, mastered: 6 },
    types: ['Long Case', 'Short Case', 'OSCE Stations', 'Viva Voce'],
    href: '/exam-centre/osce/thyroid-examination',
    isAvailable: true,
  },
  {
    id: 'guided',
    title: 'Guided Learning',
    description: 'Step-by-step concept mastery',
    icon: Compass,
    color: 'from-indigo-500 to-violet-600',
    stats: { total: 100, attempted: 15, mastered: 5 },
    features: ['Interactive Tutorials', 'Concept Maps', 'Spaced Repetition'],
    href: '#',
    isAvailable: false,
  },
];

export const subjects = [
  { id: 'surgery', name: 'Surgery', icon: Syringe, color: 'text-red-400', pyqs: 2500, cases: 80 },
  { id: 'medicine', name: 'Medicine', icon: Pill, color: 'text-blue-400', pyqs: 3200, cases: 120 },
  { id: 'obg', name: 'OBG', icon: Baby, color: 'text-pink-400', pyqs: 1800, cases: 60 },
  { id: 'pediatrics', name: 'Pediatrics', icon: Heart, color: 'text-purple-400', pyqs: 1500, cases: 45 },
  { id: 'anatomy', name: 'Anatomy', icon: Bone, color: 'text-amber-400', pyqs: 1200, cases: 20 },
  { id: 'pathology', name: 'Pathology', icon: Microscope, color: 'text-emerald-400', pyqs: 1400, cases: 35 },
  { id: 'pharmacology', name: 'Pharmacology', icon: Pill, color: 'text-cyan-400', pyqs: 1100, cases: 25 },
  { id: 'radiology', name: 'Radiology', icon: Radio, color: 'text-orange-400', pyqs: 800, cases: 40 },
  { id: 'ophthalmology', name: 'Ophthalmology', icon: Eye, color: 'text-teal-400', pyqs: 600, cases: 30 },
  { id: 'ent', name: 'ENT', icon: Ear, color: 'text-indigo-400', pyqs: 550, cases: 25 },
];

export const featuredSimulations = [
  {
    id: 'acute-appendicitis',
    title: 'Acute Appendicitis',
    description: 'A 22-year-old male with right iliac fossa pain for 12 hours...',
    difficulty: 'Medium' as const,
    duration: '20 min',
    subject: 'Surgery',
    skills: ['History', 'Examination', 'McBurney\'s Point', 'Rovsing\'s Sign'],
    completionRate: 0,
    rating: 4.9,
    isNew: true,
    isAvailable: true,
  },
  {
    id: 'acute-abdomen',
    title: 'Acute Abdomen Emergency',
    description: 'A 45-year-old male presents with severe abdominal pain...',
    difficulty: 'Hard' as const,
    duration: '25 min',
    subject: 'Surgery',
    skills: ['History', 'Examination', 'Differential Diagnosis', 'Investigation Selection'],
    completionRate: 67,
    rating: 4.8,
    isAvailable: false,
  },
  {
    id: 'chest-pain',
    title: 'Chest Pain Evaluation',
    description: 'A 60-year-old diabetic female with crushing chest pain...',
    difficulty: 'Medium' as const,
    duration: '20 min',
    subject: 'Medicine',
    skills: ['ECG Interpretation', 'Cardiac Enzymes', 'Risk Stratification'],
    completionRate: 72,
    rating: 4.9,
    isAvailable: false,
  },
  {
    id: 'labor-management',
    title: 'Normal Labor Management',
    description: 'A primigravida at 39 weeks presents in early labor...',
    difficulty: 'Medium' as const,
    duration: '30 min',
    subject: 'OBG',
    skills: ['Partograph', 'Fetal Monitoring', 'Stage Recognition', 'Delivery'],
    completionRate: 58,
    rating: 4.7,
    isAvailable: false,
  },
];

export const guidedPathways = [
  {
    id: 'surgery-essentials',
    title: 'Surgery Essentials',
    modules: 12,
    completed: 4,
    description: 'Master core surgical concepts step-by-step',
    nextTopic: 'Acute Appendicitis',
    estimatedTime: '45 min',
  },
  {
    id: 'medicine-diagnostics',
    title: 'Medicine Diagnostics',
    modules: 15,
    completed: 7,
    description: 'Learn systematic diagnostic approaches',
    nextTopic: 'Approach to Anemia',
    estimatedTime: '30 min',
  },
  {
    id: 'emergency-protocols',
    title: 'Emergency Protocols',
    modules: 8,
    completed: 2,
    description: 'Critical emergency management pathways',
    nextTopic: 'Anaphylaxis Management',
    estimatedTime: '25 min',
  },
];

export const recentActivity = [
  { type: 'pyq', title: 'NEET-PG 2024 - Surgery', score: '45/50', time: '2 hours ago' },
  { type: 'simulation', title: 'Diabetic Ketoacidosis', score: '88%', time: 'Yesterday' },
  { type: 'mcq', title: 'Hepatobiliary - 25 MCQs', score: '21/25', time: '2 days ago' },
  { type: 'practical', title: 'Long Case: Thyroid Swelling', score: 'Pass', time: '3 days ago' },
];
