-- NucleuX Academy - ATOM v2: Memory System
-- Migration: 010_atom_memory
-- Date: 2026-02-22
-- Spec: docs/specs/ATOM_MEMORY_SPEC.md, docs/specs/ATOM_GATEWAY_SPEC.md
--
-- This migration sets up:
-- 1. atom_conversations — conversation archive (resumable, searchable)
-- 2. atom_user_memory — persistent student knowledge state with vector embeddings
-- 3. atom_proactive_insights — Heartbeat-driven notifications
-- 4. search_memories() RPC — semantic memory search for Memorist agent
-- 5. RLS policies (users own their own data)

-- =====================================================
-- 1. ATOM CONVERSATIONS TABLE
-- =====================================================
-- Stores full conversation history for replay and resume.
-- Each conversation belongs to a user and a room.
-- Messages stored as JSONB array: [{ role, content, timestamp, agentId? }]

CREATE TABLE IF NOT EXISTS atom_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- Conversation context
  room TEXT NOT NULL,                     -- 'desk' | 'library' | 'classroom' | 'training' | 'cbme' | 'community' | 'arena' | 'backstage' | 'studio'
  title TEXT,                             -- Auto-generated summary after first few messages
  topic_slug TEXT,                        -- Topic being discussed (if room is Library/Training)

  -- Message history
  messages JSONB NOT NULL DEFAULT '[]',   -- Array of ATOMMessage objects
  -- Expected shape per message:
  -- {
  --   "role": "user" | "assistant" | "system",
  --   "content": "...",
  --   "timestamp": "2026-02-22T10:00:00Z",
  --   "agentId": "retriever" | null,
  --   "agentLabel": "Retriever" | null
  -- }

  -- Metadata
  metadata JSONB DEFAULT '{}',
  -- Expected shape:
  -- {
  --   "messageCount": 12,
  --   "compactedAt": "2026-02-22T11:00:00Z",
  --   "compactedSummary": "...",
  --   "tokensUsed": 15000,
  --   "lastActiveAgents": ["retriever", "memorist"]
  -- }

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 2. ATOM USER MEMORY TABLE
-- =====================================================
-- Persistent student knowledge state with vector embeddings.
-- The Memorist agent reads before generation and writes after.
-- 7 memory types with per-type decay rates (see decay cron below).

CREATE TABLE IF NOT EXISTS atom_user_memory (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- Memory classification (7 types — see ATOM_MEMORY_SPEC.md)
  memory_type TEXT NOT NULL CHECK (memory_type IN (
    'topic_mastery',        -- Student has demonstrated understanding
    'weak_area',            -- Student repeatedly struggles with concept
    'preference',           -- Learning style preferences
    'insight',              -- ATOM's observation about learning patterns
    'goal',                 -- Exam targets and ambitions
    'study_pattern',        -- Observed study behavior patterns
    'clinical_connection'   -- Breakthrough learning moments
  )),

  -- Memory content (natural language — human-readable notes about the student)
  content TEXT NOT NULL,

  -- Vector embedding (BGE-small-en-v1.5, 384 dimensions)
  -- Used for semantic search when retrieving relevant memories
  embedding vector(384),

  -- Relevance score (decays daily, resets to 1.0 on access)
  -- Decay rates by type:
  --   topic_mastery: 0.99/day (~69 day half-life)
  --   weak_area: 0.97/day (~23 day half-life)
  --   preference: 0.995/day (~138 day half-life)
  --   insight: 0.97/day (~23 day half-life)
  --   goal: 0.995/day (~138 day half-life)
  --   study_pattern: 0.97/day (~23 day half-life)
  --   clinical_connection: 0.99/day (~69 day half-life)
  relevance_score FLOAT DEFAULT 1.0 CHECK (relevance_score >= 0 AND relevance_score <= 1),

  -- Context: where and when this memory was created
  source_room TEXT,                       -- Room where memory was observed
  topic_slug TEXT,                        -- Related topic (if applicable)

  -- Archival: set when memory decays below threshold
  expires_at TIMESTAMPTZ,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 3. ATOM PROACTIVE INSIGHTS TABLE
-- =====================================================
-- Heartbeat-driven notifications generated by the Gateway.
-- Checked periodically (every 5 minutes of active use).
-- Delivered via Supabase Realtime → toast notification + widget badge.

CREATE TABLE IF NOT EXISTS atom_proactive_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- Insight classification (6 types)
  type TEXT NOT NULL CHECK (type IN (
    'study_nudge',          -- "You haven't studied Surgery in 3 days — your weak areas are decaying"
    'spaced_rep_due',       -- "12 retrieval cards are due today — 5 in Pharmacology"
    'streak_alert',         -- "Your 7-day streak is at risk! Study 10 minutes to keep it alive"
    'exam_countdown',       -- "42 days to NEET-PG — here's your priority list"
    'weak_area_alert',      -- "Your Hepatobiliary weak areas are fading from memory — review recommended"
    'memory_insight'        -- "You've mastered 80% of Cardiac Physiology — time to connect to Pharmacology"
  )),

  -- Display content
  title TEXT NOT NULL,                    -- Short headline for toast/card
  message TEXT NOT NULL,                  -- Full insight message
  action_url TEXT,                        -- Deep link: e.g., '/library/surgery/hepatobiliary/cholelithiasis'

  -- State
  is_read BOOLEAN DEFAULT FALSE,
  is_dismissed BOOLEAN DEFAULT FALSE,

  -- Extra data for frontend rendering
  metadata JSONB DEFAULT '{}',
  -- Expected shape:
  -- {
  --   "priority": "high" | "medium" | "low",
  --   "relatedTopics": ["cholelithiasis", "portal-hypertension"],
  --   "dueCards": 12,
  --   "streakDays": 7,
  --   "examDaysRemaining": 42
  -- }

  -- Timestamp
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 4. INDEXES
-- =====================================================

-- atom_conversations indexes
CREATE INDEX IF NOT EXISTS idx_conversations_user
  ON atom_conversations (user_id);

CREATE INDEX IF NOT EXISTS idx_conversations_user_room
  ON atom_conversations (user_id, room);

CREATE INDEX IF NOT EXISTS idx_conversations_updated
  ON atom_conversations (user_id, updated_at DESC);

-- atom_user_memory indexes
CREATE INDEX IF NOT EXISTS idx_memory_user
  ON atom_user_memory (user_id);

-- HNSW index for fast semantic memory search
CREATE INDEX IF NOT EXISTS idx_memory_embedding
  ON atom_user_memory
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Composite: user + type (for filtered reads like "all weak_areas for user")
CREATE INDEX IF NOT EXISTS idx_memory_user_type
  ON atom_user_memory (user_id, memory_type);

-- Composite: user + source_room (for room-scoped memory reads)
CREATE INDEX IF NOT EXISTS idx_memory_user_room
  ON atom_user_memory (user_id, source_room);

-- Index for relevance-based queries (active memories only)
CREATE INDEX IF NOT EXISTS idx_memory_relevance
  ON atom_user_memory (user_id, relevance_score DESC)
  WHERE relevance_score >= 0.1;

-- atom_proactive_insights indexes
CREATE INDEX IF NOT EXISTS idx_insights_user_unread
  ON atom_proactive_insights (user_id, is_read)
  WHERE is_read = FALSE AND is_dismissed = FALSE;

CREATE INDEX IF NOT EXISTS idx_insights_user_created
  ON atom_proactive_insights (user_id, created_at DESC);

-- =====================================================
-- 5. SEMANTIC MEMORY SEARCH (RPC FUNCTION)
-- =====================================================
-- Used by the Memorist agent during pre-generation read phase.
-- Finds memories semantically similar to the current query.

CREATE OR REPLACE FUNCTION search_memories(
  p_user_id UUID,
  p_embedding vector(384),
  p_limit INTEGER DEFAULT 5,
  p_min_score FLOAT DEFAULT 0.3
)
RETURNS TABLE (
  id UUID,
  memory_type TEXT,
  content TEXT,
  relevance_score FLOAT,
  similarity FLOAT,
  source_room TEXT,
  topic_slug TEXT,
  created_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    m.id,
    m.memory_type,
    m.content,
    m.relevance_score,
    (1 - (m.embedding <=> p_embedding))::FLOAT AS similarity,
    m.source_room,
    m.topic_slug,
    m.created_at
  FROM atom_user_memory m
  WHERE
    m.user_id = p_user_id
    AND m.embedding IS NOT NULL
    AND m.relevance_score >= 0.1
    AND (1 - (m.embedding <=> p_embedding)) >= p_min_score
  ORDER BY similarity DESC
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- =====================================================
-- 6. MEMORY DECAY FUNCTION
-- =====================================================
-- Called by a daily cron (Supabase Edge Function or pg_cron).
-- Applies per-type decay rates and archives expired memories.

CREATE OR REPLACE FUNCTION apply_memory_decay()
RETURNS void AS $$
BEGIN
  -- Apply decay based on memory type
  UPDATE atom_user_memory
  SET
    relevance_score = relevance_score * CASE memory_type
      WHEN 'topic_mastery'      THEN 0.99    -- ~69 day half-life
      WHEN 'weak_area'          THEN 0.97    -- ~23 day half-life
      WHEN 'preference'         THEN 0.995   -- ~138 day half-life
      WHEN 'insight'            THEN 0.97    -- ~23 day half-life
      WHEN 'goal'               THEN 0.995   -- ~138 day half-life
      WHEN 'study_pattern'      THEN 0.97    -- ~23 day half-life
      WHEN 'clinical_connection' THEN 0.99   -- ~69 day half-life
      ELSE 0.97
    END,
    updated_at = NOW()
  WHERE relevance_score >= 0.1;

  -- Archive memories that have decayed below threshold
  UPDATE atom_user_memory
  SET
    relevance_score = 0,
    expires_at = NOW(),
    updated_at = NOW()
  WHERE relevance_score < 0.1 AND relevance_score > 0;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 7. CLEANUP FUNCTION FOR PROACTIVE INSIGHTS
-- =====================================================
-- Deletes insights older than 30 days (per data retention policy).

CREATE OR REPLACE FUNCTION cleanup_proactive_insights()
RETURNS void AS $$
BEGIN
  DELETE FROM atom_proactive_insights
  WHERE created_at < NOW() - INTERVAL '30 days';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 8. RLS POLICIES
-- =====================================================

-- atom_conversations: Users own their conversations
ALTER TABLE atom_conversations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users own their conversations"
  ON atom_conversations
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id);

-- atom_user_memory: Users own their memories
ALTER TABLE atom_user_memory ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users own their memories"
  ON atom_user_memory
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id);

-- atom_proactive_insights: Users own their insights
ALTER TABLE atom_proactive_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users own their insights"
  ON atom_proactive_insights
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id);

-- =====================================================
-- 9. UPDATED_AT TRIGGERS
-- =====================================================
-- Reuse the update_updated_at() function from migration 009.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_atom_conversations'
  ) THEN
    CREATE TRIGGER set_updated_at_atom_conversations
      BEFORE UPDATE ON atom_conversations
      FOR EACH ROW
      EXECUTE FUNCTION update_updated_at();
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_atom_user_memory'
  ) THEN
    CREATE TRIGGER set_updated_at_atom_user_memory
      BEFORE UPDATE ON atom_user_memory
      FOR EACH ROW
      EXECUTE FUNCTION update_updated_at();
  END IF;
END $$;

-- =====================================================
-- 10. ENABLE REALTIME FOR PROACTIVE INSIGHTS
-- =====================================================
-- Supabase Realtime broadcasts new insights to the client
-- for toast notifications and widget badge updates.

ALTER PUBLICATION supabase_realtime ADD TABLE atom_proactive_insights;

-- =====================================================
-- 11. COMMENTS
-- =====================================================

COMMENT ON TABLE atom_conversations IS 'ATOM v2 conversation archive. Stores full message history per conversation for replay and resume. See docs/specs/ATOM_MEMORY_SPEC.md';
COMMENT ON TABLE atom_user_memory IS 'Persistent student knowledge state with BGE-small embeddings. 7 memory types with relevance decay. Managed by Memorist agent. See docs/specs/ATOM_MEMORY_SPEC.md';
COMMENT ON TABLE atom_proactive_insights IS 'Heartbeat-driven notifications (study nudges, streak alerts, exam countdowns). Delivered via Supabase Realtime. See docs/specs/ATOM_GATEWAY_SPEC.md';
COMMENT ON COLUMN atom_user_memory.memory_type IS '7 types: topic_mastery, weak_area, preference, insight, goal, study_pattern, clinical_connection';
COMMENT ON COLUMN atom_user_memory.relevance_score IS 'Decays daily by type-specific rate. Resets to 1.0 when accessed. Archived at < 0.1';
COMMENT ON FUNCTION search_memories IS 'Semantic memory search for Memorist agent. Finds memories similar to query embedding with relevance threshold.';
COMMENT ON FUNCTION apply_memory_decay IS 'Daily cron function: applies per-type decay rates and archives expired memories. Run at 3 AM UTC.';
COMMENT ON FUNCTION cleanup_proactive_insights IS 'Periodic cleanup: deletes proactive insights older than 30 days per data retention policy.';
